# Values of team with names to pass to scraper function in correct format
teams = {
    'Arizona Cardinals': 'Arizona',
    'Atlanta Falcons': 'Atlanta',
    'Buffalo Bills': 'Buffalo',
    'Baltimore Ravens': 'Baltimore',
     'Carolina Panthers': 'Carolina',
     'Cincinnati Bengals': 'Cincinnati',
     'Cleveland Browns': 'Cleveland',
     'Chicago Bears': 'Chicago',
     'Dallas Cowboys': 'Dallas',
     'Denver Broncos': 'Denver',
     'Detroit Lions': 'Detroit',
     'Green Bay Packers': 'Green Bay',
     'Houston Texans': 'Houston',
     'Indianapolis Colts': 'Indianapolis',
     'Kansas City Chiefs': 'Kansas City',
     'Los Angeles Chargers' : 'Los Angeles Chargers',
     'Los Angeles Rams': 'Los Angeles Rams',
     'Jacksonville Jaguars': 'Jacksonville',
     'Miami Dolphins': 'Miami',
     'Minnesota Vikings': 'Minnesota',
     'New England Patrios': 'New England',
     'New Orleans Saints': 'New Orleans',
     'New York Giants': 'New York Giants',
     'New York Jets': 'New York Jets',
     'Las Vegas Raiders': 'Las Vegas',
     'Philadelphia Eagles': 'Philadelphia',
     'San Fransisco 49ers': 'San Fransisco',
     'Seattle Seahawks': 'Seattle',
     'Pittsburgh Steelers': 'Pittsburgh',
     'Tampa Bay Buccaneers': 'Tampa Bay',
     'Tennessee Titans': 'Tennessee',
     'Washington Football Team': 'Washington'
}